services:
  db:
    build:
      context: .
      dockerfile: ./db/dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB} 
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    hostname: localhost
    container_name: postgres-db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: